---
- name: Install HTTPD and Start the Service
  hosts: all
  become: yes

  vars:
    package_name: httpd
    service_name: httpd

  tasks:
    - name: Install HTTPD
      yum:
        name: "{{ package_name }}"
        state: present
      tags:
        - install
        - httpd

    - name: Start HTTPD Service
      service:
        name: "{{ service_name }}"
        state: started
        enabled: yes
      tags:
        - start
        - httpd
