---
- name: Copying a file to remote systems
  hosts: all
  become: yes

  tasks:
    - name: Creating the file and copying it to the destination
      copy:
        src: /home/text.yaml
        dest: /tmp/
        owner: root
        group: root
        mode: "0644"
        backup: yes
