---
- name: File Module
  hosts: all
  become: yes  # Ensure root privileges

  tasks:
    - name: Create a directory first
      file:
        path: /tmp/myfolder
        state: directory
        owner: praveen
        group: praveen
        mode: "0755"

    - name: Create a file inside the directory
      file:
        path: /tmp/myfolder/newfile.yml  # File inside the directory
        state: touch  # Ensures the file exists
        owner: praveen
        group: praveen
        mode: "0644"  # Standard file permissions
