---
- name: Change file permissions
  hosts: all
  become: yes  # Needed if modifying files owned by root

  tasks:
    - name: Change permission using octal mode
      file:
        path: /tmp/myfile.yml
        mode: "0640"  # Equivalent to u=r, g=rw, o= (no permissions)
