---
- name: Copy the script from local to remote host and execute it
  hosts: all
  become: yes

  tasks:
    - name: Copy the script to the destination
      copy:
        src: /home/test.sh
        dest: /tmp/test.sh
        owner: praveen
        group: praveen
        mode: "0755"
        backup: yes
      tags:
        - copy
        - script

    - name: Execute the script
      shell: /tmp/test.sh
      tags:
        - execute
        - script
