---
- name: Copy and run a script
  hosts: all
  tasks:
    - name: Copy script to remote host
      copy:
        src: test.sh  # Local script path
        dest: /tmp/test.sh  # Remote destination
        mode: '0755'  # Ensure the script is executable

    - name: Execute the script
      shell: /tmp/test.sh
